# Generated by Django 4.2.2 on 2023-06-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('transportation', models.CharField(choices=[('A', 'Airplane'), ('T', 'Train'), ('D', 'Drive'), ('B', 'Bus')], default='A', max_length=1)),
                ('accomodations', models.CharField(choices=[('H', 'Hotel'), ('A', 'AirBnB'), ('F', 'Friend')], default='H', max_length=1)),
            ],
        ),
    ]
