# Generated by Django 4.2.2 on 2023-06-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_itinerary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ['-date', 'time']},
        ),
    ]
