# Generated by Django 4.2.2 on 2023-06-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_destination_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='accomodations',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='destination',
            name='transportation',
            field=models.CharField(max_length=100),
        ),
    ]
