# Generated by Django 4.2.2 on 2023-08-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_blog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='destination_name',
            field=models.CharField(max_length=100, verbose_name='Journey'),
        ),
    ]
